In [1]:
# ==========================================
# Cell 1: 导入工具包与设置伪装参数
# ==========================================

# requests 是用来模拟浏览器发送网络请求的库 (拿取网页源码)
import requests 
# BeautifulSoup 是用来像切蛋糕一样解析复杂 HTML 网页的库 (提取我们需要的数据)
from bs4 import BeautifulSoup 

# 1. 伪装自己 (User-Agent)
# 建议把这里的字符串换成你在 chrome://version/ 里查到的你自己的 UA
# 这样服务器会认为：“哦，这是一个用 Windows 的真实玩家在用 Chrome 浏览器访问我。”
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36 Edg/146.0.0.0',
    'Accept-Language': 'en-US,en;q=0.9', # 告诉服务器我接受英文网页
    # 下面这行很重要，很多现代网站要求加上这个防盗链或来源标识
    'Referer': 'https://www.google.com/' 
}

# 目标 URL (CS2 职业选手参数列表页面)
TARGET_URL = 'https://prosettings.net/lists/cs2/'

print("✅ 设置完毕，准备就绪。")

✅ 设置完毕，准备就绪。

In [2]:
# ==========================================
# Cell 2: 发送请求，侦察敌情
# 技巧：如果这个 Cell 成功了，以后就不需要重复运行它了，直接解析 html_content 即可
# ==========================================

print(f"🕵️‍♂️ 开始对目标发送请求: {TARGET_URL}")

# requests.get 就像是你在浏览器输入网址并按下回车
# timeout=15 意味着如果 15 秒网站还没响应，就报错，防止程序死等
response = requests.get(TARGET_URL, headers=HEADERS, timeout=15)

# HTTP 状态码常识：200=成功，403=被拒绝，404=找不到页面，500=服务器崩溃
if response.status_code == 200:
    print("✅ 突破防线！成功获取网页响应。")
    
    # 将获取到的纯文本 HTML 代码保存到变量中
    html_content = response.text 
    
    # 召唤 BeautifulSoup 解析器，将文本转化为树状结构，方便我们后续按标签查找
    soup = BeautifulSoup(html_content, 'html.parser')
    
    # 试着提取网页的标题 <title> 标签，验证是不是正确的页面
    title = soup.title.string if soup.title else "未找到标题"
    print(f"📌 获取到的网页标题为: {title}")
    
    # 看看我们到底抓下来多少个字符的代码（了解数据规模）
    print(f"📄 网页 HTML 源码总字符数: {len(html_content)}")

elif response.status_code == 403:
    print("❌ 遭到 403 拦截！网站启用了高级反爬 (可能是 Cloudflare/Datadome)。")
    print("返回内容片段:", response.text[:200]) # 打印一点错误信息看看原因

else:
    print(f"⚠️ 出现意外状态码: {response.status_code}")

🕵️‍♂️ 开始对目标发送请求: https://prosettings.net/lists/cs2/
✅ 突破防线！成功获取网页响应。
📌 获取到的网页标题为: CS2 Pro Settings and Gear List
📄 网页 HTML 源码总字符数: 1858999

In [3]:
# ==========================================
# Cell 3: 精确打击 - 分析选手数据的 HTML 结构
# ==========================================
import re

# 我们用当前 Top 级别的狙击手 ZywOo 作为“诱饵”来定位
target_player = "ZywOo" 
print(f"🔍 正在 1.8MB 的源码中搜索: {target_player} ...")

# 在 BeautifulSoup 解析后的树状结构中，寻找包含该名字的所有文本节点 (忽略大小写)
player_nodes = soup.find_all(string=re.compile(target_player, re.IGNORECASE))

if not player_nodes:
    print("❌ 没找到该选手！数据可能被隐藏在复杂的 JSON 中。")
else:
    print(f"🎯 找到了 {len(player_nodes)} 处包含 '{target_player}' 的文本！")
    print("-" * 50)
    
    # 提取第一处匹配的位置
    first_match = player_nodes[0]
    
    # 向上寻找它的“祖父”节点，通常这会包含这一整行（一整个选手）的数据
    # 使用 try-except 防止因为层级不够而报错
    try:
        # .parent 是一层一层向外找包裹它的 HTML 标签
        row_html = first_match.parent.parent.parent 
        
        print("💡 提取到该选手所在区块的 HTML 代码片段：\n")
        # .prettify() 可以把凌乱的代码排版得整整齐齐，[:800] 是为了只看前 800 个字符
        print(row_html.prettify()[:800]) 
        
    except Exception as e:
        print("提取 HTML 结构时出错:", e)

🔍 正在 1.8MB 的源码中搜索: ZywOo ...
🎯 找到了 10 处包含 'ZywOo' 的文本！
--------------------------------------------------
💡 提取到该选手所在区块的 HTML 代码片段：

<ol class="menu menu--players">
 <li class="menu-item">
  <a href="https://prosettings.net/players/donk/">
   <picture class="edge-images-container" style="--content-visibility: auto; --max-width: 30px; --width: 30px">
    <img alt="donk" class="attachment-30x30 size-30x30 is-prosettings-cf-local" decoding="async" height="30" src="https://prosettings.net/wp-content/uploads/donk-30x30-fitcontain-s1.webp" srcset="https://prosettings.net/wp-content/uploads/donk-30x30-fitcontain-s1.webp 30w, https://prosettings.net/wp-content/uploads/donk-30x30-15x-fitcontain-s1.webp 45w, https://prosettings.net/wp-content/uploads/donk-30x30-2x-fitcontain-s1.webp 60w" width="30"/>
   </picture>
   donk
  </a>
 </li>
 <li class="menu-item">
  <a href="https://prosettings.net/players/m0nesy/">
   <picture class=

In [4]:
# ==========================================
# Cell 4: 终极收割 - 提取表格数据并导出 CSV
# ==========================================
import pandas as pd

print("🚜 开始启动表格收割机...")

# 1. 找到网页中所有的 <tr> (表格行)
rows = soup.find_all('tr')

player_data_list = []
headers =[]

# 2. 遍历每一行，把数据提出来
for row in rows:
    # 提取当前行所有的单元格 <th> (表头) 或 <td> (具体数据)
    cells = row.find_all(['th', 'td'])
    
    # 提取纯文本内容，并去除首尾的换行符和空格
    # separator=' ' 是为了防止网页里隐藏的图标和文字粘连在一起
    cell_texts =[cell.get_text(separator=' ', strip=True) for cell in cells]
    
    # 如果这一行是空的，跳过
    if not cell_texts:
        continue
        
    # 3. 寻找表头 (Column Names)
    # 如果这一行里同时包含了 'Player' 和 'DPI'，那它肯定是表头！
    if 'Player' in cell_texts and 'DPI' in cell_texts:
        headers = cell_texts
        print(f"🎯 成功锁定表头: {headers}")
        
    # 4. 提取选手数据
    # 排除掉表头行，并且只要列数足够多的行（过滤掉网页上可能存在的其他乱七八糟的短表格）
    elif len(cell_texts) >= 5: 
        player_data_list.append(cell_texts)

print(f"✅ 成功提取了 {len(player_data_list)} 名职业选手的原始数据！")

# ---------------------------------------------------------
# 将散乱的列表转化为 Pandas DataFrame (数据分析的绝对核心)
# ---------------------------------------------------------

# 防止某些行的数据比表头短或长，我们做一个对齐处理
cleaned_data =[]
for data in player_data_list:
    if len(data) >= len(headers):
        cleaned_data.append(data[:len(headers)]) # 截断多余的列
    else:
        cleaned_data.append(data + [None] * (len(headers) - len(data))) # 不足的列用 None 补齐

# 创建 DataFrame！
df = pd.DataFrame(cleaned_data, columns=headers)

# 5. 导出为 CSV 文件
csv_filename = "cs2_pro_raw.csv"
# index=False 代表不要把行号 (0, 1, 2...) 写进文件
# encoding='utf-8-sig' 是为了防止带有特殊字符的名字（如一些俄语/北欧字母）在 Excel 里乱码
df.to_csv(csv_filename, index=False, encoding='utf-8-sig')

print(f"💾 任务完成！数据已成功保存到本地：{csv_filename}")

# 6. 打印前 5 行数据预览一下战果
display(df.head())

🚜 开始启动表格收割机...
🎯 成功锁定表头: ['', 'Team', 'Player', 'Role', 'Mouse', 'HZ', 'DPI', 'Sens', 'eDPI', 'Zoom Sens', 'Monitor', 'GPU', 'Resolution', 'Aspect Ratio', 'Scaling Mode', 'Mousepad', 'Keyboard', 'Headset', 'Chair']
✅ 成功提取了 873 名职业选手的原始数据！
💾 任务完成！数据已成功保存到本地：cs2_pro_raw.csv

,,Team,Player,Role,Mouse,HZ,DPI,Sens,eDPI,Zoom Sens,Monitor,GPU,Resolution,Aspect Ratio,Scaling Mode,Mousepad,Keyboard,Headset,Chair
0,,Team Vitality,ZywOo,Sniper,Pulsar ZywOo The Chosen Mouse White,1000,400,2,800.00,1,ZOWIE XL2566K,RTX 3080,1280x960,4:3,Stretched,The Chosen Mousepad,ASUS ROG Falchion Ace HFX ZywOo Edition,ASUS ROG Pelta,Secretlab Titan Evo Vitality Edition
1,,Team Vitality,ropz,Rifler,Razer DeathAdder V3 HyperSpeed,2000,400,1.77,708,1,ZOWIE XL2586X+,RTX 4090,1920x1080,16:9,Native,Zowie Mousepad (Unreleased),ASUS ROG Falchion Ace 75 HE White,SteelSeries Arctis Nova Pro Wireless,Anthros V2
2,,Team Vitality,flameZ,Rifler,ZOWIE EC2-DW Grey (Unreleased),1000,400,3,1200.00,1.1,ZOWIE XL2566K,RTX 3080,1280x960,4:3,Stretched,Xtrfy GP4,ASUS ROG Falchion Ace 75 HE Black,Logitech G Pro X Headset,Secretlab Titan Evo Vitality Edition
3,,Team Vitality,apEX,Rifler,ZOWIE EC2-DW Black,1000,400,1.91,764.00,1,ZOWIE XL2566K,RTX 2080 Ti,1280x960,4:3,Stretched,ZOWIE G-TR,ASUS ROG Falchion Ace HFX Black,ASUS ROG Delta II,Secretlab Titan Evo Vitality Edition
4,,Team Vitality,mezii,Rifler,VAXEE XE V2 Fluorescent Green,2000,400,2.2,880.00,1,ZOWIE XL2566K,,1280x960,4:3,Stretched,BanKs Collection Heavy Claw by ESPTIGER,ASUS ROG Falchion Ace 75 HE White,ASUS ROG Pelta,Secretlab Titan Evo Vitality Edition

In [5]:
# ==========================================
# Cell 5: 获取所有选手的详情页 URL
# ==========================================
print("🔗 开始提取选手专属链接...")

# 创建一个字典，用来存 { "donk": "https://prosettings.net/players/donk/", ... }
player_urls = {}

# 重新遍历一次刚刚存好的 rows (包含所有 <tr> 标签)
for row in rows:
    # 找到这一行里所有的 <a> 标签 (也就是超链接)
    links = row.find_all('a')
    
    for link in links:
        href = link.get('href')
        # 确保这个链接存在，并且是通向选手个人页面的
        if href and 'players/' in href:
            player_name = link.get_text(strip=True)
            # 存入字典
            if player_name:
                player_urls[player_name] = href

print(f"✅ 成功提取了 {len(player_urls)} 个选手的个人主页链接！")

# 随便打印前 3 个看看对不对
# list(player_urls.items())[:3] 会把字典转成列表并切片前三个
print("🔗 链接示例预览：")
for name, url in list(player_urls.items())[:3]:
    print(f"{name} -> {url}")

🔗 开始提取选手专属链接...
✅ 成功提取了 872 个选手的个人主页链接！
🔗 链接示例预览：
ZywOo -> https://prosettings.net/players/zywoo/
ropz -> https://prosettings.net/players/ropz/
flameZ -> https://prosettings.net/players/flamez/

In [6]:
# ==========================================
# Cell 6: 探路详情页 (以 donk 为例)
# ==========================================
import time # 导入时间库，准备做防封禁停顿

# 我们拿 donk 开刀，如果你喜欢别的选手可以换他的名字
test_player = "donk"
# 如果前面成功拿到了链接，我们就用拿到的；如果没有，硬编码一个备用
test_url = player_urls.get(test_player, "https://prosettings.net/players/donk/")

print(f"🕵️‍♂️ 正在潜入 {test_player} 的个人主页: {test_url}")

# 发送请求
detail_response = requests.get(test_url, headers=HEADERS, timeout=15)

if detail_response.status_code == 200:
    print(f"✅ 成功进入 {test_player} 的详情页！")
    detail_soup = BeautifulSoup(detail_response.text, 'html.parser')
    
    # 【核心任务】：在个人主页里，所有的设置通常会被归类在一个个小盒子里
    # 比如 "Mouse Settings", "Video Settings", "Crosshair"
    # 我们试着找找网页里有没有包含 "Resolution" (分辨率) 的文本
    import re
    res_nodes = detail_soup.find_all(string=re.compile("Resolution", re.IGNORECASE))
    
    if res_nodes:
        print("\n🎯 找到有关 Resolution 的线索了！")
        first_res = res_nodes[0]
        # 向上找它的父节点，看看网页是怎么排版的
        try:
            res_html = first_res.parent.parent
            print("💡 包含分辨率区块的 HTML 代码片段：\n")
            print(res_html.prettify()[:500])
        except Exception as e:
            print("提取节点出错:", e)
    else:
        print("❌ 没找到 Resolution，页面结构可能比较特殊。")

else:
    print(f"❌ 请求失败，状态码: {detail_response.status_code}")

🕵️‍♂️ 正在潜入 donk 的个人主页: https://prosettings.net/players/donk/
✅ 成功进入 donk 的详情页！

🎯 找到有关 Resolution 的线索了！
💡 包含分辨率区块的 HTML 代码片段：

<tr class="format-select field-resolution" data-field="resolution">
 <th>
  Resolution
 </th>
 <td>
  1280x960
 </td>
</tr>

In [8]:
# ==========================================
# Cell 7 [最终完美版]: 解决覆盖问题并全量抓取！
# ==========================================
import time
import random
import pandas as pd

print("🚀 启动最终版全量收割机... (大概需要几分钟，请耐心等待)")

all_players_detailed_data = []

# 这次我们去掉 [:5]，直接遍历 player_urls 字典里的所有人！
total_targets = len(player_urls)

for index, (player_name, profile_url) in enumerate(player_urls.items()):
    # 打印进度条
    print(f"[{index+1}/{total_targets}] 抓取 {player_name} ...", end=" ")
    
    try:
        response = requests.get(profile_url, headers=HEADERS, timeout=10)
        
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            
            player_info = {
                'Player': player_name,
                'Profile_URL': profile_url
            }
            
            detail_rows = soup.find_all('tr')
            for row in detail_rows:
                th = row.find('th')
                td = row.find('td')
                
                if th and td:
                    # 提取基础键值
                    original_key = th.get_text(strip=True)
                    value = td.get_text(strip=True)
                    
                    # 🌟 修复键冲突 Bug：如果字典里已经有这个键了，我们就加后缀
                    key = original_key
                    counter = 2
                    while key in player_info:
                        key = f"{original_key}_{counter}"
                        counter += 1
                        
                    # 安全存入字典
                    player_info[key] = value
            
            all_players_detailed_data.append(player_info)
            print("✅ OK")
            
        else:
            print(f"❌ 失败，状态码: {response.status_code}")
            
    except Exception as e:
        print(f"⚠️ 报错: {e}")
    
    # 防封禁机制，稍微停顿
    time.sleep(random.uniform(1.0, 2.5))

print("\n🎉 全部抓取完成！开始保存数据...")

df_detailed = pd.DataFrame(all_players_detailed_data)

# 保存为终极 RAW 数据
final_csv_name = "cs2_pro_detailed_RAW.csv"
df_detailed.to_csv(final_csv_name, index=False, encoding='utf-8-sig')

print(f"💾 完美！全部数据已保存至：{final_csv_name} (共 {len(df_detailed)} 行，{len(df_detailed.columns)} 列)")

# 预览一下修复后的前 5 行数据
display(df_detailed.head())

🚀 启动最终版全量收割机... (大概需要几分钟，请耐心等待)
[1/872] 抓取 ZywOo ... ✅ OK
[2/872] 抓取 ropz ... ✅ OK
[3/872] 抓取 flameZ ... ✅ OK
[4/872] 抓取 apEX ... ✅ OK
[5/872] 抓取 mezii ... ✅ OK
[6/872] 抓取 Jamppi ... ✅ OK
[7/872] 抓取 donk ... ✅ OK
[8/872] 抓取 sh1ro ... ✅ OK
[9/872] 抓取 magixx ... ✅ OK
[10/872] 抓取 zont1x ... ✅ OK
[11/872] 抓取 chopper ... ✅ OK
[12/872] 抓取 tN1R ... ✅ OK
[13/872] 抓取 Jimpphat ... ✅ OK
[14/872] 抓取 Spinx ... ✅ OK
[15/872] 抓取 Brollan ... ✅ OK
[16/872] 抓取 xertioN ... ✅ OK
[17/872] 抓取 torzsi ... ✅ OK
[18/872] 抓取 m0NESY ... ✅ OK
[19/872] 抓取 NiKo ... ✅ OK
[20/872] 抓取 TeSeS ... ✅ OK
[21/872] 抓取 kyxsan ... ✅ OK
[22/872] 抓取 kyousuke ... ✅ OK
[23/872] 抓取 bLitz ... ✅ OK
[24/872] 抓取 Techno4K ... ✅ OK
[25/872] 抓取 mzinho ... ✅ OK
[26/872] 抓取 910 ... ✅ OK
[27/872] 抓取 cobra ... ✅ OK
[28/872] 抓取 XANTARES ... ✅ OK
[29/872] 抓取 woxic ... ✅ OK
[30/872] 抓取 Wicadia ... ✅ OK
[31/872] 抓取 MAJ3R ... ✅ OK
[32/872] 抓取 Soulfly ... ✅ OK
[33/872] 抓取 b1t ... ✅ OK
[34/872] 抓取 w0nderful ... ✅ OK
[35/872] 抓取 iM ... ✅ OK
[36/872] 抓取 Aleksib ... ✅ OK
[37/872] 抓取 ANGE1 ... ✅ OK
[38/872] 抓取 makazze ... ✅ OK
[39/872] 抓取 huNter ... ✅ OK
[40/872] 抓取 Nertz ... ✅ OK
[41/872] 抓取 SunPayus ... ✅ OK
[42/872] 抓取 HeavyGod ... ✅ OK
[43/872] 抓取 matys ... ✅ OK
[44/872] 抓取 Snax ... ✅ OK
[45/872] 抓取 hypex ... ✅ OK
[46/872] 抓取 REZ ... ✅ OK
[47/872] 抓取 Kursy ... ✅ OK
[48/872] 抓取 sl3nd ... ✅ OK
[49/872] 抓取 Tauson ... ✅ OK
[50/872] 抓取 PR ... ✅ OK
[51/872] 抓取 jL ... ✅ OK
[52/872] 抓取 EliGE ... ✅ OK
[53/872] 抓取 siuhy ... ✅ OK
[54/872] 抓取 NAF ... ✅ OK
[55/872] 抓取 ultimate ... ✅ OK
[56/872] 抓取 ShahZaM ... ✅ OK
[57/872] 抓取 malbsMd ... ✅ OK
[58/872] 抓取 Twistzz ... ✅ OK
[59/872] 抓取 Frozen ... ✅ OK
[60/872] 抓取 broky ... ✅ OK
[61/872] 抓取 karrigan ... ✅ OK
[62/872] 抓取 olofmeister ... ✅ OK
[63/872] 抓取 jcobbb ... ✅ OK
[64/872] 抓取 nilo ... ✅ OK
[65/872] 抓取 xfl0ud ... ✅ OK
[66/872] 抓取 Chr1zN ... ✅ OK
[67/872] 抓取 susp ... ✅ OK
[68/872] 抓取 yxngstxr ... ✅ OK
[69/872] 抓取 alkarenn ... ✅ OK
[70/872] 抓取 Perfecto ... ✅ OK
[71/872] 抓取 fame ... ✅ OK
[72/872] 抓取 b1st ... ✅ OK
[73/872] 抓取 mir ... ✅ OK
[74/872] 抓取 tO0RO ... ✅ OK
[75/872] 抓取 FL1T ... ✅ OK
[76/872] 抓取 HooXi ... ✅ OK
[77/872] 抓取 jabbi ... ✅ OK
[78/872] 抓取 Staehr ... ✅ OK
[79/872] 抓取 phzy ... ✅ OK
[80/872] 抓取 ryu ... ✅ OK
[81/872] 抓取 FalleN ... ✅ OK
[82/872] 抓取 YEKINDAR ... ✅ OK
[83/872] 抓取 kscerato ... ✅ OK
[84/872] 抓取 yuurih ... ✅ OK
[85/872] 抓取 molodoy ... ✅ OK
[86/872] 抓取 misutaaa ... ✅ OK
[87/872] 抓取 bodyy ... ✅ OK
[88/872] 抓取 Maka ... ✅ OK
[89/872] 抓取 Lucky ... ✅ OK
[90/872] 抓取 Ex3rcice ... ✅ OK
[91/872] 抓取 Graviti ... ✅ OK
[92/872] 抓取 kl1m ... ✅ OK
[93/872] 抓取 brnz4n ... ✅ OK
[94/872] 抓取 LNZ ... ✅ OK
[95/872] 抓取 saffee ... ✅ OK
[96/872] 抓取 insani ... ✅ OK
[97/872] 抓取 venomzera ... ✅ OK
[98/872] 抓取 npl ... ✅ OK
[99/872] 抓取 headtr1ck ... ✅ OK
[100/872] 抓取 alex666 ... ✅ OK
[101/872] 抓取 esenthial ... ✅ OK
[102/872] 抓取 kensizor ... ✅ OK
[103/872] 抓取 sjuush ... ✅ OK
[104/872] 抓取 Snappi ... ✅ OK
[105/872] 抓取 r1nkle ... ✅ OK
[106/872] 抓取 ewjerkz ... ✅ OK
[107/872] 抓取 xKacpersky ... ✅ OK
[108/872] 抓取 cairne ... ✅ OK
[109/872] 抓取 lux ... ✅ OK
[110/872] 抓取 latto ... ✅ OK
[111/872] 抓取 dumau ... ✅ OK
[112/872] 抓取 arT ... ✅ OK
[113/872] 抓取 n1ssim ... ✅ OK
[114/872] 抓取 saadzin ... ✅ OK
[115/872] 抓取 biguzera ... ✅ OK
[116/872] 抓取 nqz ... ✅ OK
[117/872] 抓取 dav1deuS ... ✅ OK
[118/872] 抓取 vsm ... ✅ OK
[119/872] 抓取 snow ... ✅ OK
[120/872] 抓取 piriajr ... ✅ OK
[121/872] 抓取 DANK1NG ... ✅ OK
[122/872] 抓取 JamYoung ... ✅ OK
[123/872] 抓取 Mercury ... ✅ OK
[124/872] 抓取 SLOWLY ... ✅ OK
[125/872] 抓取 Moseyuh ... ✅ OK
[126/872] 抓取 Jee ... ✅ OK
[127/872] 抓取 Zero ... ✅ OK
[128/872] 抓取 Starry ... ✅ OK
[129/872] 抓取 z4kr ... ✅ OK
[130/872] 抓取 Westmelon ... ✅ OK
[131/872] 抓取 EmiliaQAQ ... ✅ OK
[132/872] 抓取 C4LLM3SU3 ... ✅ OK
[133/872] 抓取 JDC ... ✅ OK
[134/872] 抓取 Krimbo ... ✅ OK
[135/872] 抓取 blameF ... ✅ OK
[136/872] 抓取 tabseN ... ✅ OK
[137/872] 抓取 faveN ... ✅ OK
[138/872] 抓取 prosus ... ✅ OK
[139/872] 抓取 gr1ks ... ✅ OK
[140/872] 抓取 HexT ... ✅ OK
[141/872] 抓取 reck ... ✅ OK
[142/872] 抓取 Peeping ... ✅ OK
[143/872] 抓取 nEMANHA ... ✅ OK
[144/872] 抓取 fr3nd ... ✅ OK
[145/872] 抓取 jks ... ✅ OK
[146/872] 抓取 Vexite ... ✅ OK
[147/872] 抓取 regali ... ✅ OK
[148/872] 抓取 INS ... ✅ OK
[149/872] 抓取 story ... ✅ OK
[150/872] 抓取 nettik ... ✅ OK
[151/872] 抓取 Ax1Le ... ✅ OK
[152/872] 抓取 Boombl4 ... ✅ OK
[153/872] 抓取 s1ren ... ✅ OK
[154/872] 抓取 Artfr0st ... ✅ OK
[155/872] 抓取 d1Ledez ... ✅ OK
[156/872] 抓取 Magnojez ... ✅ OK
[157/872] 抓取 shalfey ... ✅ OK
[158/872] 抓取 KaiR0N- ... ✅ OK
[159/872] 抓取 Xant3r ... ✅ OK
[160/872] 抓取 SYPH0 ... ✅ OK
[161/872] 抓取 khaN ... ✅ OK
[162/872] 抓取 riskyb0b ... ✅ OK
[163/872] 抓取 1eer ... ✅ OK
[164/872] 抓取 sowalio ... ✅ OK
[165/872] 抓取 cadiaN ... ✅ OK
[166/872] 抓取 arrozdoce ... ✅ OK
[167/872] 抓取 Nexius ... ✅ OK
[168/872] 抓取 spooke ... ✅ OK
[169/872] 抓取 adamb ... ✅ OK
[170/872] 抓取 FL4MUS ... ✅ OK
[171/872] 抓取 s1n ... ✅ OK
[172/872] 抓取 slaxz- ... ✅ OK
[173/872] 抓取 dephh ... ✅ OK
[174/872] 抓取 Swisher ... ✅ OK
[175/872] 抓取 JBa ... ✅ OK
[176/872] 抓取 Lake ... ✅ OK
[177/872] 抓取 Sonic ... ✅ OK
[178/872] 抓取 Jeorge ... ✅ OK
[179/872] 抓取 Grim ... ✅ OK
[180/872] 抓取 oSee ... ✅ OK
[181/872] 抓取 autimatic ... ✅ OK
[182/872] 抓取 nitr0 ... ✅ OK
[183/872] 抓取 Ethan ... ✅ OK
[184/872] 抓取 s0m ... ✅ OK
[185/872] 抓取 br0 ... ✅ OK
[186/872] 抓取 nosraC ... ✅ OK
[187/872] 抓取 F1KU ... ✅ OK
[188/872] 抓取 kRaSnaL ... ✅ OK
[189/872] 抓取 sdy ... ✅ OK
[190/872] 抓取 Neityu ... ✅ OK
[191/872] 抓取 podi ... ✅ OK
[192/872] 抓取 coldzera ... ✅ OK
[193/872] 抓取 togs ... ✅ OK
[194/872] 抓取 ksloks ... ✅ OK
[195/872] 抓取 WOOD7 ... ✅ OK
[196/872] 抓取 matios ... ✅ OK
[197/872] 抓取 naitte ... ✅ OK
[198/872] 抓取 pancc ... ✅ OK
[199/872] 抓取 mizu ... ✅ OK
[200/872] 抓取 n0rb3r7 ... ✅ OK
[201/872] 抓取 noway ... ✅ OK
[202/872] 抓取 chelo ... ✅ OK
[203/872] 抓取 skullz ... ✅ OK
[204/872] 抓取 VINI ... ✅ OK
[205/872] 抓取 levi ... ✅ OK
[206/872] 抓取 decenty ... ✅ OK
[207/872] 抓取 wastzera ... ✅ OK
[208/872] 抓取 Shr ... ✅ OK
[209/872] 抓取 ROUX ... ✅ OK
[210/872] 抓取 cool4st ... ✅ OK
[211/872] 抓取 Efire ... ✅ OK
[212/872] 抓取 ariucle ... ✅ OK
[213/872] 抓取 rmn ... ✅ OK
[214/872] 抓取 Fazery ... ✅ OK
[215/872] 抓取 kodak ... ✅ OK
[216/872] 抓取 R3ZLOO ... ✅ OK
[217/872] 抓取 satsu ... ✅ OK
[218/872] 抓取 Lucaozy ... ✅ OK
[219/872] 抓取 zevy ... ✅ OK
[220/872] 抓取 exit ... ✅ OK
[221/872] 抓取 kye ... ✅ OK
[222/872] 抓取 mlhzin ... ✅ OK
[223/872] 抓取 Buzz ... ✅ OK
[224/872] 抓取 TMB ... ✅ OK
[225/872] 抓取 nicoodoz ... ✅ OK
[226/872] 抓取 Anlelele ... ✅ OK
[227/872] 抓取 nut nut ... ✅ OK
[228/872] 抓取 dennyslaw ... ✅ OK
[229/872] 抓取 Kjaerbye ... ✅ OK
[230/872] 抓取 Bibu ... ✅ OK
[231/872] 抓取 hallzerk ... ✅ OK
[232/872] 抓取 Senzu ... ✅ OK
[233/872] 抓取 Kvem ... ✅ OK
[234/872] 抓取 JT ... ✅ OK
[235/872] 抓取 try ... ✅ OK
[236/872] 抓取 nicx ... ✅ OK
[237/872] 抓取 Jame ... ✅ OK
[238/872] 抓取 BELCHONOKK ... ✅ OK
[239/872] 抓取 zweih ... ✅ OK
[240/872] 抓取 xiELO ... ✅ OK
[241/872] 抓取 nota ... ✅ OK
[242/872] 抓取 KRIMZ ... ✅ OK
[243/872] 抓取 fear ... ✅ OK
[244/872] 抓取 Br4tkO ... ✅ OK
[245/872] 抓取 maden ... ✅ OK
[246/872] 抓取 jackasmo ... ✅ OK
[247/872] 抓取 jambo ... ✅ OK
[248/872] 抓取 robo ... ✅ OK
[249/872] 抓取 somebody ... ✅ OK
[250/872] 抓取 Kaze ... ✅ OK
[251/872] 抓取 Marek ... ✅ OK
[252/872] 抓取 TiGeR ... ✅ OK
[253/872] 抓取 Summer ... ✅ OK
[254/872] 抓取 ChildKing ... ✅ OK
[255/872] 抓取 L1haNg ... ✅ OK
[256/872] 抓取 XELLOW ... ✅ OK
[257/872] 抓取 s0und ... ✅ OK
[258/872] 抓取 Blytz ... ✅ OK
[259/872] 抓取 refrezh ... ✅ OK
[260/872] 抓取 raalz ... ✅ OK
[261/872] 抓取 kraghen ... ✅ OK
[262/872] 抓取 cej0t ... ✅ OK
[263/872] 抓取 Flayy ... ✅ OK
[264/872] 抓取 bnox ... ✅ OK
[265/872] 抓取 Zellsis ... ✅ OK
[266/872] 抓取 Xeppaa ... ✅ OK
[267/872] 抓取 rigoN ... ✅ OK
[268/872] 抓取 Calyx ... ✅ OK
[269/872] 抓取 imoRR ... ✅ OK
[270/872] 抓取 DemQQ ... ✅ OK
[271/872] 抓取 mASKED ... ✅ OK
[272/872] 抓取 EMSTAR ... ✅ OK
[273/872] 抓取 Woro2k ... ✅ OK
[274/872] 抓取 jottAAA ... ✅ OK
[275/872] 抓取 jresy ... ✅ OK
[276/872] 抓取 Grashog ... ✅ OK
[277/872] 抓取 bajmi ... ✅ OK
[278/872] 抓取 olimp ... ✅ OK
[279/872] 抓取 Markeloff ... ✅ OK
[280/872] 抓取 reiko ... ✅ OK
[281/872] 抓取 SaMey ... ✅ OK
[282/872] 抓取 moonwalk ... ✅ OK
[283/872] 抓取 nellozz ... ✅ OK
[284/872] 抓取 Gnøffe ... ✅ OK
[285/872] 抓取 tOPZ ... ✅ OK
[286/872] 抓取 Krad ... ✅ OK
[287/872] 抓取 Alv ... ✅ OK
[288/872] 抓取 meyern ... ✅ OK
[289/872] 抓取 max ... ✅ OK
[290/872] 抓取 dgt ... ✅ OK
[291/872] 抓取 HUASOPEEK ... ✅ OK
[292/872] 抓取 luchov ... ✅ OK
[293/872] 抓取 urban0 ... ✅ OK
[294/872] 抓取 land1n ... ✅ OK
[295/872] 抓取 lcf ... ✅ OK
[296/872] 抓取 CSO ... ✅ OK
[297/872] 抓取 MistR ... ✅ OK
[298/872] 抓取 Zyphon ... ✅ OK
[299/872] 抓取 Mol011 ... ✅ OK
[300/872] 抓取 Beccie ... ✅ OK
[301/872] 抓取 acoR ... ✅ OK
[302/872] 抓取 Cabbi ... ✅ OK
[303/872] 抓取 Patti ... ✅ OK
[304/872] 抓取 Brooxsy ... ✅ OK
[305/872] 抓取 Djoko ... ✅ OK
[306/872] 抓取 Skadoodle ... ✅ OK
[307/872] 抓取 steel ... ✅ OK
[308/872] 抓取 buda ... ✅ OK
[309/872] 抓取 timo ... ✅ OK
[310/872] 抓取 Noktse ... ✅ OK
[311/872] 抓取 tomaszin ... ✅ OK
[312/872] 抓取 Aaron ... ✅ OK
[313/872] 抓取 Dytor ... ✅ OK
[314/872] 抓取 manguss ... ✅ OK
[315/872] 抓取 Rainwaker ... ✅ OK
[316/872] 抓取 afro ... ✅ OK
[317/872] 抓取 Bymas ... ✅ OK
[318/872] 抓取 AZUWU ... ✅ OK
[319/872] 抓取 Gizmy ... ✅ OK
[320/872] 抓取 ScreaM ... ✅ OK
[321/872] 抓取 Nivera ... ✅ OK
[322/872] 抓取 lauNX ... ✅ OK
[323/872] 抓取 cmtry ... ✅ OK
[324/872] 抓取 dem0n ... ✅ OK
[325/872] 抓取 Krabeni ... ✅ OK
[326/872] 抓取 dziugss ... ✅ OK
[327/872] 抓取 h4rn ... ✅ OK
[328/872] 抓取 t9rnay ... ✅ OK
[329/872] 抓取 Razzmo ... ✅ OK
[330/872] 抓取 drop ... ✅ OK
[331/872] 抓取 history ... ✅ OK
[332/872] 抓取 Chay ... ✅ OK
[333/872] 抓取 kauez ... ✅ OK
[334/872] 抓取 felps ... ✅ OK
[335/872] 抓取 HEN1 ... ✅ OK
[336/872] 抓取 MICHU ... ✅ OK
[337/872] 抓取 SHiPZ ... ✅ OK
[338/872] 抓取 CYPHER ... ✅ OK
[339/872] 抓取 ztr ... ✅ OK
[340/872] 抓取 Banjo ... ✅ OK
[341/872] 抓取 Matheos ... ✅ OK
[342/872] 抓取 volt ... ✅ OK
[343/872] 抓取 Jorko ... ✅ OK
[344/872] 抓取 emi ... ✅ OK
[345/872] 抓取 c0llins ... ✅ OK
[346/872] 抓取 VLDN ... ✅ OK
[347/872] 抓取 Kind0 ... ✅ OK
[348/872] 抓取 nopzy ... ✅ OK
[349/872] 抓取 SLIGHT ... ✅ OK
[350/872] 抓取 Fruitcupx ... ✅ OK
[351/872] 抓取 Wolffe ... ✅ OK
[352/872] 抓取 laser ... ✅ OK
[353/872] 抓取 atarax1a ... ✅ OK
[354/872] 抓取 deco ... ✅ OK
[355/872] 抓取 kNgV- ... ✅ OK
[356/872] 抓取 boltz ... ✅ OK
[357/872] 抓取 clax ... ✅ OK
[358/872] 抓取 Norwi ... ✅ OK
[359/872] 抓取 h0kz ... ✅ OK
[360/872] 抓取 Patsi ... ✅ OK
[361/872] 抓取 r3salt ... ✅ OK
[362/872] 抓取 danistzz ... ✅ OK
[363/872] 抓取 allu ... ✅ OK
[364/872] 抓取 HENU ... ✅ OK
[365/872] 抓取 Icarus ... ✅ OK
[366/872] 抓取 snapy ... ✅ OK
[367/872] 抓取 TMKj ... ✅ OK
[368/872] 抓取 NOPEEJ ... ✅ OK
[369/872] 抓取 stadodo ... ✅ OK
[370/872] 抓取 SHOOWTiMe ... ✅ OK
[371/872] 抓取 JOTA ... ✅ OK
[372/872] 抓取 captainMo ... ✅ OK
[373/872] 抓取 Gratisfaction ... ✅ OK
[374/872] 抓取 Melavi ... ✅ OK
[375/872] 抓取 darchevile ... ✅ OK
[376/872] 抓取 Enzo ... ✅ OK
[377/872] 抓取 Nami ... ✅ OK
[378/872] 抓取 yvro ... ✅ OK
[379/872] 抓取 chudy ... ✅ OK
[380/872] 抓取 AdrieN ... ✅ OK
[381/872] 抓取 danoco ... ✅ OK
[382/872] 抓取 b4rtiN ... ✅ OK
[383/872] 抓取 lash ... ✅ OK
[384/872] 抓取 bsd ... ✅ OK
[385/872] 抓取 yepz ... ✅ OK
[386/872] 抓取 fl0m ... ✅ OK
[387/872] 抓取 Cooper ... ✅ OK
[388/872] 抓取 Trucklover86 ... ✅ OK
[389/872] 抓取 dex ... ✅ OK
[390/872] 抓取 JW ... ✅ OK
[391/872] 抓取 maxster ... ✅ OK
[392/872] 抓取 Ro1f ... ✅ OK
[393/872] 抓取 bobeksde ... ✅ OK
[394/872] 抓取 MahaR ... ✅ OK
[395/872] 抓取 MisteM ... ✅ OK
[396/872] 抓取 NickyB ... ✅ OK
[397/872] 抓取 Boye ... ✅ OK
[398/872] 抓取 Valde ... ✅ OK
[399/872] 抓取 salazar ... ✅ OK
[400/872] 抓取 IceBerg ... ✅ OK
[401/872] 抓取 Leakz ... ✅ OK
[402/872] 抓取 uli ... ✅ OK
[403/872] 抓取 xns ... ✅ OK
[404/872] 抓取 pesadelo ... ✅ OK
[405/872] 抓取 HObbit ... ✅ OK
[406/872] 抓取 interz ... ✅ OK
[407/872] 抓取 Qikert ... ✅ OK
[408/872] 抓取 lattykk ... ✅ OK
[409/872] 抓取 mirbit ... ✅ OK
[410/872] 抓取 shokz ... ✅ OK
[411/872] 抓取 juanflatroo ... ✅ OK
[412/872] 抓取 gxx ... ✅ OK
[413/872] 抓取 sinnopsyy ... ✅ OK
[414/872] 抓取 maaryy ... ✅ OK
[415/872] 抓取 miksozzz ... ✅ OK
[416/872] 抓取 syncD ... ✅ OK
[417/872] 抓取 AyeZ ... ✅ OK
[418/872] 抓取 hayanh ... ✅ OK
[419/872] 抓取 MartinezSa ... ✅ OK
[420/872] 抓取 sausol ... ✅ OK
[421/872] 抓取 alex ... ✅ OK
[422/872] 抓取 mopoz ... ✅ OK
[423/872] 抓取 dav1g ... ✅ OK
[424/872] 抓取 MiGHTYMAX ... ✅ OK
[425/872] 抓取 stressarN ... ✅ OK
[426/872] 抓取 ZEDKO ... ✅ OK
[427/872] 抓取 beastik ... ✅ OK
[428/872] 抓取 SHOCK ... ✅ OK
[429/872] 抓取 MoriiSko ... ✅ OK
[430/872] 抓取 MoDo ... ✅ OK
[431/872] 抓取 Kisserek ... ✅ OK
[432/872] 抓取 Pepo ... ✅ OK
[433/872] 抓取 doc ... ✅ OK
[434/872] 抓取 eraa ... ✅ OK
[435/872] 抓取 PlesseN ... ✅ OK
[436/872] 抓取 twist ... ✅ OK
[437/872] 抓取 MaiL09 ... ✅ OK
[438/872] 抓取 Avid ... ✅ OK
[439/872] 抓取 upE ... ✅ OK
[440/872] 抓取 xccurate ... ✅ OK
[441/872] 抓取 niko ... ✅ OK
[442/872] 抓取 tarik ... ✅ OK
[443/872] 抓取 gokushima ... ✅ OK
[444/872] 抓取 device ... ✅ OK
[445/872] 抓取 rain ... ✅ OK
[446/872] 抓取 sirah ... ✅ OK
[447/872] 抓取 poiii ... ✅ OK
[448/872] 抓取 Ag1l ... ✅ OK
[449/872] 抓取 ay0k ... ✅ OK
[450/872] 抓取 Joey ... ✅ OK
[451/872] 抓取 Nikodeon ... ✅ OK
[452/872] 抓取 opdust ... ✅ OK
[453/872] 抓取 xelex ... ✅ OK
[454/872] 抓取 Dementor ... ✅ OK
[455/872] 抓取 Jackinho ... ✅ OK
[456/872] 抓取 forsyy ... ✅ OK
[457/872] 抓取 isak ... ✅ OK
[458/872] 抓取 Plopski ... ✅ OK
[459/872] 抓取 Dragon ... ✅ OK
[460/872] 抓取 L00m1 ... ✅ OK
[461/872] 抓取 ritchiE ... ✅ OK
[462/872] 抓取 Rip ... ✅ OK
[463/872] 抓取 Lobanjica ... ✅ OK
[464/872] 抓取 glowiing ... ✅ OK
[465/872] 抓取 alpha ... ✅ OK
[466/872] 抓取 Mokuj1n ... ✅ OK
[467/872] 抓取 lov1kus ... ✅ OK
[468/872] 抓取 notineki ... ✅ OK
[469/872] 抓取 bl1x1 ... ✅ OK
[470/872] 抓取 FenomeN ... ✅ OK
[471/872] 抓取 brzer ... ✅ OK
[472/872] 抓取 iDISBALANCE ... ✅ OK
[473/872] 抓取 KENSI ... ✅ OK
[474/872] 抓取 nafany ... ✅ OK
[475/872] 抓取 TRAVIS ... ✅ OK
[476/872] 抓取 sstiNiX ... ✅ OK
[477/872] 抓取 austin ... ✅ OK
[478/872] 抓取 d4rty ... ✅ OK
[479/872] 抓取 Tapewaare ... ✅ OK
[480/872] 抓取 controlez ... ✅ OK
[481/872] 抓取 sk0R ... ✅ OK
[482/872] 抓取 nin9 ... ✅ OK
[483/872] 抓取 Bart4k ... ✅ OK
[484/872] 抓取 yAmi ... ✅ OK
[485/872] 抓取 xerolte ... ✅ OK
[486/872] 抓取 Veccil ... ✅ OK
[487/872] 抓取 fostar ... ✅ OK
[488/872] 抓取 1mpala ... ✅ OK
[489/872] 抓取 easy ... ✅ OK
[490/872] 抓取 Annihilation ... ✅ OK
[491/872] 抓取 kabal ... ✅ OK
[492/872] 抓取 dobu ... ✅ OK
[493/872] 抓取 Zesta ... ✅ OK
[494/872] 抓取 AccuracyTG ... ✅ OK
[495/872] 抓取 MiQ ... ✅ OK
[496/872] 抓取 DARE ... ✅ OK
[497/872] 抓取 adeX ... ✅ OK
[498/872] 抓取 Drop ... ✅ OK
[499/872] 抓取 CoJoMo ... ✅ OK
[500/872] 抓取 s1mple ... ✅ OK
[501/872] 抓取 electronic ... ✅ OK
[502/872] 抓取 krazy ... ✅ OK
[503/872] 抓取 aragornN ... ✅ OK
[504/872] 抓取 jkaem ... ✅ OK
[505/872] 抓取 MUTiRiS ... ✅ OK
[506/872] 抓取 aNdu ... ✅ OK
[507/872] 抓取 honda ... ✅ OK
[508/872] 抓取 kory ... ✅ OK
[509/872] 抓取 Porya ... ✅ OK
[510/872] 抓取 tAk ... ✅ OK
[511/872] 抓取 Draken ... ✅ OK
[512/872] 抓取 Lekr0 ... ✅ OK
[513/872] 抓取 Svedjehed ... ✅ OK
[514/872] 抓取 Sapec ... ✅ OK
[515/872] 抓取 jocab ... ✅ OK
[516/872] 抓取 bevve ... ✅ OK
[517/872] 抓取 virtuoso ... ✅ OK
[518/872] 抓取 nestee ... ✅ OK
[519/872] 抓取 bondik ... ✅ OK
[520/872] 抓取 Marix ... ✅ OK
[521/872] 抓取 BOROS ... ✅ OK
[522/872] 抓取 BnTeT ... ✅ OK
[523/872] 抓取 Freeman ... ✅ OK
[524/872] 抓取 tomiko ... ✅ OK
[525/872] 抓取 ohnepixel ... ✅ OK
[526/872] 抓取 EspiranTo ... ✅ OK
[527/872] 抓取 stanislaw ... ✅ OK
[528/872] 抓取 FaNg ... ✅ OK
[529/872] 抓取 NEOFRAG ... ✅ OK
[530/872] 抓取 Pechyn ... ✅ OK
[531/872] 抓取 Levi ... ✅ OK
[532/872] 抓取 K1-FiDa ... ✅ OK
[533/872] 抓取 simke ... ✅ OK
[534/872] 抓取 brutmonster ... ✅ OK
[535/872] 抓取 Cjoffo ... ✅ OK
[536/872] 抓取 aVN ... ✅ OK
[537/872] 抓取 swicher ... ✅ OK
[538/872] 抓取 SALO_MUX ... ✅ OK
[539/872] 抓取 weqt2 ... ✅ OK
[540/872] 抓取 mediocrity ... ✅ OK
[541/872] 抓取 hades ... ✅ OK
[542/872] 抓取 Aunkere ... ✅ OK
[543/872] 抓取 deko ... ✅ OK
[544/872] 抓取 StRoGo ... ✅ OK
[545/872] 抓取 m3wsu ... ✅ OK
[546/872] 抓取 tried ... ✅ OK
[547/872] 抓取 Skejs ... ✅ OK
[548/872] 抓取 Skodo ... ✅ OK
[549/872] 抓取 thamlike ... ✅ OK
[550/872] 抓取 GA1De ... ✅ OK
[551/872] 抓取 SinK ... ✅ OK
[552/872] 抓取 PKL ... ✅ OK
[553/872] 抓取 hardzao ... ✅ OK
[554/872] 抓取 Burmylov ... ✅ OK
[555/872] 抓取 KAISER ... ✅ OK
[556/872] 抓取 Tuurtle ... ✅ OK
[557/872] 抓取 ninjaZ ... ✅ OK
[558/872] 抓取 ponter ... ✅ OK
[559/872] 抓取 zock ... ✅ OK
[560/872] 抓取 nyezin ... ✅ OK
[561/872] 抓取 fREQ ... ✅ OK
[562/872] 抓取 pepe ... ✅ OK
[563/872] 抓取 cptkurtka023 ... ✅ OK
[564/872] 抓取 zeRRoFIX ... ✅ OK
[565/872] 抓取 ANa ... ✅ OK
[566/872] 抓取 twenty3 ... ✅ OK
[567/872] 抓取 naz ... ✅ OK
[568/872] 抓取 dea ... ✅ OK
[569/872] 抓取 shane ... ✅ OK
[570/872] 抓取 neaLaN ... ✅ OK
[571/872] 抓取 CRUC1AL ... ✅ OK
[572/872] 抓取 Moose ... ✅ OK
[573/872] 抓取 keis ... ✅ OK
[574/872] 抓取 Masi ... ✅ OK
[575/872] 抓取 flying ... ✅ OK
[576/872] 抓取 nukkye ... ✅ OK
[577/872] 抓取 szejn ... ✅ OK
[578/872] 抓取 Griller ... ✅ OK
[579/872] 抓取 KWERTZZ ... ✅ OK
[580/872] 抓取 zewts ... ✅ OK
[581/872] 抓取 ERSIN ... ✅ OK
[582/872] 抓取 Ed1m ... ✅ OK
[583/872] 抓取 Kiy0o ... ✅ OK
[584/872] 抓取 majky ... ✅ OK
[585/872] 抓取 birdfromsky ... ✅ OK
[586/872] 抓取 b0RUP ... ✅ OK
[587/872] 抓取 Keoz ... ✅ OK
[588/872] 抓取 b0denmaster ... ✅ OK
[589/872] 抓取 Vegi ... ✅ OK
[590/872] 抓取 Dani ... ✅ OK
[591/872] 抓取 yungher ... ✅ OK
[592/872] 抓取 poppins ... ✅ OK
[593/872] 抓取 GaBi ... ✅ OK
[594/872] 抓取 OLGA ... ✅ OK
[595/872] 抓取 smooya ... ✅ OK
[596/872] 抓取 juho ... ✅ OK
[597/872] 抓取 kyuubii ... ✅ OK
[598/872] 抓取 k1to ... ✅ OK
[599/872] 抓取 Altekz ... ✅ OK
[600/872] 抓取 delle ... ✅ OK
[601/872] 抓取 miwo ... ✅ OK
[602/872] 抓取 innocent ... ✅ OK
[603/872] 抓取 b1elany ... ✅ OK
[604/872] 抓取 Qlocuu ... ✅ OK
[605/872] 抓取 hfah ... ✅ OK
[606/872] 抓取 grecu ... ✅ OK
[607/872] 抓取 clockzi ... ✅ OK
[608/872] 抓取 Olaie ... ✅ OK
[609/872] 抓取 NucleonZ ... ✅ OK
[610/872] 抓取 VENO ... ✅ OK
[611/872] 抓取 vilga ... ✅ OK
[612/872] 抓取 Zana ... ✅ OK
[613/872] 抓取 Qiyarah ... ✅ OK
[614/872] 抓取 Nayomy ... ✅ OK
[615/872] 抓取 aiM ... ✅ OK
[616/872] 抓取 suns1de ... ✅ OK
[617/872] 抓取 Kylar ... ✅ OK
[618/872] 抓取 TOAO ... ✅ OK
[619/872] 抓取 mynio ... ✅ OK
[620/872] 抓取 KEi ... ✅ OK
[621/872] 抓取 DGL ... ✅ OK
[622/872] 抓取 Kunai ... ✅ OK
[623/872] 抓取 Ayteel ... ✅ OK
[624/872] 抓取 Queenix ... ✅ OK
[625/872] 抓取 Maze ... ✅ OK
[626/872] 抓取 n1Xen ... ✅ OK
[627/872] 抓取 bekker ... ✅ OK
[628/872] 抓取 stesso ... ✅ OK
[629/872] 抓取 Viggo ... ✅ OK
[630/872] 抓取 Goosebreeder ... ✅ OK
[631/872] 抓取 DeStiNy ... ✅ OK
[632/872] 抓取 nython ... ✅ OK
[633/872] 抓取 Walco ... ✅ OK
[634/872] 抓取 MarkE ... ✅ OK
[635/872] 抓取 junior ... ✅ OK
[636/872] 抓取 Cryptic ... ✅ OK
[637/872] 抓取 motm ... ✅ OK
[638/872] 抓取 Wolfy ... ✅ OK
[639/872] 抓取 cxzi ... ✅ OK
[640/872] 抓取 freshie ... ✅ OK
[641/872] 抓取 buster ... ✅ OK
[642/872] 抓取 ICY ... ✅ OK
[643/872] 抓取 OWNER ... ✅ OK
[644/872] 抓取 Bambosh ... ✅ OK
[645/872] 抓取 tatazin ... ✅ OK
[646/872] 抓取 n1cks ... ✅ OK
[647/872] 抓取 mawth ... ✅ OK
[648/872] 抓取 aliStair ... ✅ OK
[649/872] 抓取 Liazz ... ✅ OK
[650/872] 抓取 dexter ... ✅ OK
[651/872] 抓取 NickelBack ... ✅ OK
[652/872] 抓取 Lack1 ... ✅ OK
[653/872] 抓取 Forester ... ✅ OK
[654/872] 抓取 El1an ... ✅ OK
[655/872] 抓取 SELLTER ... ✅ OK
[656/872] 抓取 Sdaim ... ✅ OK
[657/872] 抓取 Raijin ... ✅ OK
[658/872] 抓取 synyx ... ✅ OK
[659/872] 抓取 kreaz ... ✅ OK
[660/872] 抓取 oskar ... ✅ OK
[661/872] 抓取 nbqq ... ✅ OK
[662/872] 抓取 HS ... ✅ OK
[663/872] 抓取 Folke ... ✅ OK
[664/872] 抓取 AmaNEk ... ✅ OK
[665/872] 抓取 ex1st ... ✅ OK
[666/872] 抓取 sk1tt ... ✅ OK
[667/872] 抓取 SBT ... ✅ OK
[668/872] 抓取 POLO ... ✅ OK
[669/872] 抓取 dycha ... ✅ OK
[670/872] 抓取 hAdji ... ✅ OK
[671/872] 抓取 adamS ... ✅ OK
[672/872] 抓取 LOGAN ... ✅ OK
[673/872] 抓取 snowiee ... ✅ OK
[674/872] 抓取 swiz ... ✅ OK
[675/872] 抓取 zock9 ... ✅ OK
[676/872] 抓取 X5G7V ... ✅ OK
[677/872] 抓取 yay ... ✅ OK
[678/872] 抓取 D0cC ... ✅ OK
[679/872] 抓取 skywhywalker ... ✅ OK
[680/872] 抓取 nexa ... ✅ OK
[681/872] 抓取 Magisk ... ✅ OK
[682/872] 抓取 shox ... ✅ OK
[683/872] 抓取 DD ... ✅ OK
[684/872] 抓取 Goofy ... ✅ OK
[685/872] 抓取 Byali ... ✅ OK
[686/872] 抓取 maty ... ✅ OK
[687/872] 抓取 tudsoN ... ✅ OK
[688/872] 抓取 wiz ... ✅ OK
[689/872] 抓取 REDSTAR ... ✅ OK
[690/872] 抓取 kressy ... ✅ OK
[691/872] 抓取 keiz ... ✅ OK
[692/872] 抓取 ISSAA ... ✅ OK
[693/872] 抓取 phr ... ✅ OK
[694/872] 抓取 kolor ... ✅ OK
[695/872] 抓取 rallen ... ✅ OK
[696/872] 抓取 Surreal ... ✅ OK
[697/872] 抓取 SIXER ... ✅ OK
[698/872] 抓取 almazer ... ✅ OK
[699/872] 抓取 Nodios ... ✅ OK
[700/872] 抓取 ngiN ... ✅ OK

,Player,Profile_URL,Name,Birthday,Country,Team,DPI,Sensitivity,eDPI,Zoom Sensitivity,...,Refraction Quality,Screenshot Quality,Ambient Occlusion_3,Local Reflections,Damage FX,Resolution_10,Aspect Ratio_6,Type_2,Thickness_3,Meshes
0,ZywOo,https://prosettings.net/players/zywoo/,Mathieu Herbaut,"November 9, 2000",France,Team Vitality,400,2,800.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ropz,https://prosettings.net/players/ropz/,Robin Kool,"December 22, 1999",Estonia,Team Vitality,400,1.77,708,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,flameZ,https://prosettings.net/players/flamez/,Shahar Shushan,"June 22, 2003",Israel,Team Vitality,400,3,1200.00,1.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,apEX,https://prosettings.net/players/apex/,Dan Madesclaire,"February 22, 1993",France,Team Vitality,400,1.91,764.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mezii,https://prosettings.net/players/mezii/,William Merriman,"October 15, 1998",United Kingdom,Team Vitality,400,2.2,880.00,1.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN